services:
  mysql:
    container_name: study_mysql_container
    image: mysql:latest
    environment:
      MYSQL_DATABASE: study
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - backend
  redis:
      container_name: study_redis_container
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
        - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        - backend

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
